package com.evo.NEAT;

public enum MutationKeys {
    STEPS,
    PERTURB_CHANCE,
    WEIGHT_CHANCE,
    WEIGHT_MUTATION_CHANCE,
    NODE_MUTATION_CHANCE,
    CONNECTION_MUTATION_CHANCE,
    BIAS_CONNECTION_MUTATION_CHANCE,
    DISABLE_MUTATION_CHANCE,
    ENABLE_MUTATION_CHANCE
}
